django_hw/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework.authtoken import views

schema_view = get_schema_view(
    openapi.Info(
        title="Repository API",
        default_version="v1",
        description="No comments",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@me.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    # permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("repository.urls")),
    path("token/", views.obtain_auth_token),
    path("__reload__/", include("django_browser_reload.urls")),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

urlpatterns += staticfiles_urlpatterns()

repository/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path, reverse_lazy
from rest_framework.routers import DefaultRouter

from repository import views

router = DefaultRouter()
router.register(r"repository", views.RepositoryViewSet, basename="repository")
router.register(r"developer", views.DeveloperViewSet)
router.register(r"ticket", views.TicketViewSet)

app_name = "repository"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", views.HomePage.as_view(), name="home"),
    path("devs/", views.DevsPage.as_view()),
    path("login/", LoginView.as_view(template_name="login.html")),
    path(
        "logout/",
        LogoutView.as_view(next_page=reverse_lazy("home")),
        name="logout",
    ),
    path("profile/", views.ProfilePage.as_view()),
    path("tickets/", views.TicketsPage.as_view()),
]

repository/models.py
from datetime import datetime, timezone
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models


class UUIDMixin(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    class Meta:
        abstract = True


def get_datetime() -> datetime:
    return datetime.now(timezone.utc)


def check_date_created(dt: datetime) -> None:
    if dt > get_datetime():
        raise ValidationError(
            "Date and time is bigger than current!", params={"created": dt}
        )


class CreatedMixin(models.Model):
    created = models.DateTimeField(
        "created",
        default=get_datetime,
        null=True,
        blank=True,
        validators=[check_date_created],
    )

    class Meta:
        abstract = True


class Repository(UUIDMixin):
    name = models.TextField("name", null=False, blank=False)
    description = models.TextField("description", null=False, blank=False)
    stars = models.PositiveIntegerField(
        "stars",
        null=False,
        blank=False,
        default=0,
    )
    developers = models.ManyToManyField(
        "developer", related_name="repository_developer"
    )

    class Meta:
        db_table = '"django_hw"."repository"'
        verbose_name = "repository"
        verbose_name_plural = "repositories"

    def __str__(self):
        return f"{self.name} {self.stars} stars"


class Developer(UUIDMixin, CreatedMixin):
    name = models.TextField("name", null=False, blank=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = '"django_hw"."developer"'
        verbose_name = "developer"
        verbose_name_plural = "developers"

    def __str__(self):
        return self.name


class Ticket(UUIDMixin):
    name = models.TextField("name", null=False, blank=False)
    description = models.TextField("description", null=False, blank=False)

    class Status(models.TextChoices):
        CREATED = "created", "created"
        IN_WORK = "in work", "in work"
        DONE = "done", "done"

    status = models.TextField(
        "status", choices=Status, null=False, blank=False
    )

    repository = models.ForeignKey(
        "repository", null=False, blank=False, on_delete=models.CASCADE
    )

    class Meta:
        db_table = '"django_hw"."ticket"'
        verbose_name = "ticket"
        verbose_name_plural = "tickets"

repository/views.py
from django.views.generic import TemplateView
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from rest_framework.permissions import SAFE_METHODS, BasePermission
from rest_framework.viewsets import ModelViewSet

from repository.models import Developer, Repository, Ticket
from repository.serializers import (
    DeveloperSerializer,
    RepositorySerializer,
    TicketSerializer,
)


class MyPermission(BasePermission):
    def has_permission(self, request, view):
        if request.method in SAFE_METHODS:
            return bool(request.user and request.user.is_authenticated)
        return bool(request.user and request.user.is_superuser)


def create_viewset(model, serializer):
    class CustomViewSet(ModelViewSet):
        queryset = model.objects.all()
        serializer_class = serializer
        permission_classes = [MyPermission]
        authentication_classes = [TokenAuthentication]

    return CustomViewSet


RepositoryViewSet = create_viewset(Repository, RepositorySerializer)
DeveloperViewSet = create_viewset(Developer, DeveloperSerializer)
TicketViewSet = create_viewset(Ticket, TicketSerializer)


class HomePage(TemplateView):
    template_name = "homepage.html"

    def get_context_data(self, *args, **kwargs):
        context = super(HomePage, self).get_context_data(**kwargs)
        context["repos"] = Repository.objects.all()
        context["serializer"] = RepositorySerializer
        if self.request.user.is_authenticated:
            context["token"] = Token.objects.get(user=self.request.user)
        return context


class DevsPage(TemplateView):
    template_name = "devs.html"

    def get_context_data(self, *args, **kwargs):
        context = super(DevsPage, self).get_context_data(**kwargs)
        context["devs"] = Developer.objects.all()
        return context


class ProfilePage(TemplateView):
    template_name = "profile.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProfilePage, self).get_context_data(**kwargs)
        context["repos"] = Repository.objects.filter(
            developers=self.request.user.developer
        )
        if self.request.user.is_authenticated:
            context["token"] = Token.objects.get(user=self.request.user)
        return context


class TicketsPage(TemplateView):
    template_name = "tickets.html"

    def get_context_data(self, *args, **kwargs):
        context = super(TicketsPage, self).get_context_data(**kwargs)
        context["tickets"] = Ticket.objects.all()
        return context

templates/base.html
{% load static %}
{% load rest_framework %}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="keywords" content="youdontneedit" />
  <meta name="description" content="somedesc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>BadPractices</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>
  <header class="d-flex justify-content-center py-3 border-bottom mb-3">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a href="/" class="nav-link">Home</a>
      </li>
      <li class="nav-item">
        <a href="/devs" class="nav-link">Devs</a>
      </li>
      <li class="nav-item">
        <a href="/tickets" class="nav-link">Tickets</a>
      </li>
      <li class="nav-item">
        {% if user.username %}
      <li class="nav-item">
        <a href="/profile" class="nav-link">Profile: {{ user.developer.name }}</a>
      </li>
      <li class="nav-item">
        <form method="post" action="{% url 'repository:logout' %}">
          {% csrf_token %}
          <button type="submit" class="nav-link">Log out</button>
        </form>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="/login" class="nav-link">Log in</a>
      </li>
      {% endif %}
      </li>
    </ul>
  </header>
  {% block content %}{% endblock %}
</body>

</html>

templates/devs.html
{% extends "base.html" %}
{% block content %}
<div class="container-md">
  {% for dev in devs %}
  <div class="card p-3">
    <h3 class="card-title">User: {{dev.name}}</h3>
  </div>
  {% endfor %}
</div>
{% endblock %}

templates/homepage.html
{% extends "base.html" %}
{% load rest_framework %}
{% block content %}
<div class="container-md">
  {% if user.is_authenticated %}
  <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add-repo">
    Add repository
  </button>
  {% endif %}
  <div class="modal fade" id="add-repo">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">Add repository</h2>
        </div>
        <div class="modal-body">
          <form id="add-repo-form">
            {% csrf_token %}
            {% render_form serializer %}
            <button class="btn btn-primary" type="submit">Add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% for repo in repos %}
  <div class="card p-3">
    <h3 class="card-title">{{repo.name}}</h3>
    <p class="card-text">{{repo.description}}</p>
    <p class="card-text">Stars: {{repo.stars}}</p>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#{{repo.id}}">
      See more
    </button>
  </div>
  <div class="modal fade" id="{{repo.id}}">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">{{repo.name}}</h2>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Description: {{repo.description}}</p>
          <p>Stars: {{repo.stars}}</p>
          <h3>Developers:</h3>
          <ul class="list-group">
            {% for developer in repo.developers.all %}
            <li class="list-group-item">{{developer.name}}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<script>
  const addRepoForm = document.querySelector("#add-repo-form");
  addRepoForm.addEventListener("submit", (e) => {
    e.preventDefault();

    const formData = new FormData(addRepoForm);
    formData.append("developer", "{{user.developer.id}}")
    const formDataEntries = Array.from(formData.entries());
    const requestBody = formDataEntries.map(([key, value]) =>
      `${encodeURIComponent(key)}=${encodeURIComponent(value)}`).join('&');

    fetch("{% url 'repository:repository-list' %}", {
      method: "POST",
      headers: {
        "X-CSRFToken": document.querySelector('[name="csrfmiddlewaretoken"]').value,
        "Authorization": "Token " + "{{ token | safe }}",
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: requestBody,
    });
  });
</script>
{% endblock%}

templates/includes/fields.html
{% if form.errors %}<div class="alert alert-danger">Проверьте введённые данные!</div>{% endif %}
{% for field in form %}
  <div class="login-block form-control-lg form-group-item">
    {{ field.label_tag }} {{ field }}
    {% if field.help_text %}<p class="help">{{ field.help_text | safe }}</p>{% endif %}
  </div>
{% endfor %}

templates/includes/profile.html
<p>Username {{user.developer.name}}</p>

templates/includes/signup.html
<h1>Регистрация</h1>
<div class="form-group signup">{{ form.as_p }}</div>
<input class="btn btn-primary"
       type="submit"
       name="send"
       value="Зарегистрироваться"/>

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="px-4 py-5 my-5 text-center feedback">
    <form action="" method="post">
      {% comment %}
        csrf похоже нельзя поместить в инклуд, не рендерит
      {% endcomment %}
      {% csrf_token %}
      {% include "includes/fields.html" %}
      <button id="btn-login" class="btn btn-primary" type="submit">
        {% block view-text %}
          Войти
        {% endblock view-text %}
      </button>
    </form>
  </div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-md">
  <p>Username: {{user.developer.name}}</p>
  {% for repo in repos %}
  <div class="card p-3">
    <h3 class="card-title">{{repo.name}}</h3>
    <p class="card-text">{{repo.description}}</p>
    <p class="card-text">Stars: {{repo.stars}}</p>
    <button class="btn btn-secondary" onclick="deleteRepo('{{repo.id}}')">Delete</button>
  </div>
  {% endfor %}
</div>
<script>
  function deleteRepo(repoId) {
    fetch("{% url 'repository:repository-list' %}" + repoId, {
      method: "DELETE",
      headers: {
        "Authorization": "Token " + "{{ token | safe }}"
      }
    })
  }
</script>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="px-4 py-5 my-5 feedback">
    <form enctype="multipart/form-data" method="post" class="feedback">
      {% csrf_token %}
      {% include "includes/signup.html" %}
    </form>
  </div>
{% endblock content %}

templates/tickets.html
{% extends "base.html" %}
{% block content %}
<div class="container-md">
  {% for ticket in tickets %}
  <div class="card p-3">
    <h3 class="card-title">Repository: {{ticket.repository}}</h3>
    <h5 class="card-title">{{ticket.name}}</h5>
    <p class="card-text">Text: {{ticket.description}}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}